// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wojnyntwnwtiizijbgkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvam55bnR3bnd0aWl6aWpiZ2t4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Mjc3ODAsImV4cCI6MjA2NjAwMzc4MH0.DV7nj49efwlYAf0UTni8IDISrm-UKAL3F8yqdd923wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);